// SPDX-FileCopyrightText: 2026 Contributors to GAlMax
//
// SPDX-License-Identifier: AGPL-3.0-or-later

/// Встроенные стикерпаки по умолчанию: видны всем без настройки.
/// Источник: https://github.com/seanprashad/slackmoji (наборы parrots, party,
/// blob, blob-sign, froge, froggie, gopha, meow, shiblob).
/// Тап: загрузка на хомсервер -> обычный m.sticker.
class BundledSticker {
  final String name;
  final String assetPath;
  final String mimeType;

  const BundledSticker(this.name, this.assetPath, this.mimeType);
}

class BundledStickerPack {
  final String title;
  final List<BundledSticker> items;

  const BundledStickerPack(this.title, this.items);
}

const List<BundledStickerPack> bundledStickerPacks = [
  BundledStickerPack('Blob', [
    BundledSticker('blob_cheer', 'assets/stickers/galmax/blob-cheer.png', 'image/png'),
    BundledSticker('blob_clap_gif', 'assets/stickers/galmax/blob-clap-gif.gif', 'image/gif'),
    BundledSticker('blob_cry', 'assets/stickers/galmax/blob-cry.png', 'image/png'),
    BundledSticker('blob_dancer_gif', 'assets/stickers/galmax/blob-dancer-gif.gif', 'image/gif'),
    BundledSticker('blob_dundundun_gif', 'assets/stickers/galmax/blob-dundundun-gif.gif', 'image/gif'),
    BundledSticker('blob_frog', 'assets/stickers/galmax/blob-frog.png', 'image/png'),
    BundledSticker('blob_heart', 'assets/stickers/galmax/blob-heart.png', 'image/png'),
    BundledSticker('blob_hug', 'assets/stickers/galmax/blob-hug.png', 'image/png'),
    BundledSticker('blob_kiss', 'assets/stickers/galmax/blob-kiss.png', 'image/png'),
    BundledSticker('blob_love_gif', 'assets/stickers/galmax/blob-love-gif.gif', 'image/gif'),
    BundledSticker('blob_no', 'assets/stickers/galmax/blob-no.png', 'image/png'),
    BundledSticker('blob_ok', 'assets/stickers/galmax/blob-ok.png', 'image/png'),
    BundledSticker('blob_party', 'assets/stickers/galmax/blob-party.png', 'image/png'),
    BundledSticker('blob_party_gif', 'assets/stickers/galmax/blob-party-gif.gif', 'image/gif'),
    BundledSticker('blob_sad', 'assets/stickers/galmax/blob-sad.png', 'image/png'),
    BundledSticker('blob_shocked_gif', 'assets/stickers/galmax/blob-shocked-gif.gif', 'image/gif'),
    BundledSticker('blob_shrug', 'assets/stickers/galmax/blob-shrug.png', 'image/png'),
    BundledSticker('blob_smile', 'assets/stickers/galmax/blob-smile.png', 'image/png'),
    BundledSticker('blob_thinking', 'assets/stickers/galmax/blob-thinking.png', 'image/png'),
    BundledSticker('blob_thumbs_up', 'assets/stickers/galmax/blob-thumbs-up.png', 'image/png'),
    BundledSticker('blob_wave', 'assets/stickers/galmax/blob-wave.png', 'image/png'),
    BundledSticker('blob_wave_gif', 'assets/stickers/galmax/blob-wave-gif.gif', 'image/gif'),
    BundledSticker('blob_wink', 'assets/stickers/galmax/blob-wink.png', 'image/png'),
    BundledSticker('blob_yes', 'assets/stickers/galmax/blob-yes.png', 'image/png'),
  ]),
  BundledStickerPack('Слова', [
    BundledSticker('blob_sign_brb', 'assets/stickers/galmax/blob-sign-brb.png', 'image/png'),
    BundledSticker('blob_sign_bye', 'assets/stickers/galmax/blob-sign-bye.png', 'image/png'),
    BundledSticker('blob_sign_cya', 'assets/stickers/galmax/blob-sign-cya.png', 'image/png'),
    BundledSticker('blob_sign_gg', 'assets/stickers/galmax/blob-sign-gg.png', 'image/png'),
    BundledSticker('blob_sign_hey', 'assets/stickers/galmax/blob-sign-hey.png', 'image/png'),
    BundledSticker('blob_sign_kk', 'assets/stickers/galmax/blob-sign-kk.png', 'image/png'),
    BundledSticker('blob_sign_lmao', 'assets/stickers/galmax/blob-sign-lmao.png', 'image/png'),
    BundledSticker('blob_sign_lol', 'assets/stickers/galmax/blob-sign-lol.png', 'image/png'),
    BundledSticker('blob_sign_no', 'assets/stickers/galmax/blob-sign-no.png', 'image/png'),
    BundledSticker('blob_sign_ok', 'assets/stickers/galmax/blob-sign-ok.png', 'image/png'),
    BundledSticker('blob_sign_omg', 'assets/stickers/galmax/blob-sign-omg.png', 'image/png'),
    BundledSticker('blob_sign_pls', 'assets/stickers/galmax/blob-sign-pls.png', 'image/png'),
    BundledSticker('blob_sign_rip', 'assets/stickers/galmax/blob-sign-rip.png', 'image/png'),
    BundledSticker('blob_sign_thx', 'assets/stickers/galmax/blob-sign-thx.png', 'image/png'),
    BundledSticker('blob_sign_ty', 'assets/stickers/galmax/blob-sign-ty.png', 'image/png'),
    BundledSticker('blob_sign_yay', 'assets/stickers/galmax/blob-sign-yay.png', 'image/png'),
    BundledSticker('blob_sign_yes', 'assets/stickers/galmax/blob-sign-yes.png', 'image/png'),
  ]),
  BundledStickerPack('Froge', [
    BundledSticker('froge_angry2', 'assets/stickers/galmax/froge-angry2.png', 'image/png'),
    BundledSticker('froge_dab', 'assets/stickers/galmax/froge-dab.png', 'image/png'),
    BundledSticker('froge_dealwithit', 'assets/stickers/galmax/froge-dealwithit.png', 'image/png'),
    BundledSticker('froge_happy', 'assets/stickers/galmax/froge-happy.png', 'image/png'),
    BundledSticker('froge_happy2', 'assets/stickers/galmax/froge-happy2.gif', 'image/gif'),
    BundledSticker('froge_hug', 'assets/stickers/galmax/froge-hug.png', 'image/png'),
    BundledSticker('froge_love', 'assets/stickers/galmax/froge-love.png', 'image/png'),
    BundledSticker('froge_ok', 'assets/stickers/galmax/froge-ok.png', 'image/png'),
    BundledSticker('froge_peek', 'assets/stickers/galmax/froge-peek.png', 'image/png'),
    BundledSticker('froge_pog', 'assets/stickers/galmax/froge-pog.png', 'image/png'),
    BundledSticker('froge_sad', 'assets/stickers/galmax/froge-sad.png', 'image/png'),
    BundledSticker('froge_suspicious', 'assets/stickers/galmax/froge-suspicious.png', 'image/png'),
    BundledSticker('froge_thonk', 'assets/stickers/galmax/froge-thonk.png', 'image/png'),
    BundledSticker('froge_wave', 'assets/stickers/galmax/froge-wave.gif', 'image/gif'),
    BundledSticker('froge_wink', 'assets/stickers/galmax/froge-wink.gif', 'image/gif'),
    BundledSticker('froggie_angry', 'assets/stickers/galmax/froggie-angry.png', 'image/png'),
    BundledSticker('froggie_bonk', 'assets/stickers/galmax/froggie-bonk.png', 'image/png'),
    BundledSticker('froggie_celebrate', 'assets/stickers/galmax/froggie-celebrate.png', 'image/png'),
    BundledSticker('froggie_cry', 'assets/stickers/galmax/froggie-cry.png', 'image/png'),
    BundledSticker('froggie_heart', 'assets/stickers/galmax/froggie-heart.png', 'image/png'),
    BundledSticker('froggie_sip', 'assets/stickers/galmax/froggie-sip.png', 'image/png'),
    BundledSticker('froggie_vibing_gif', 'assets/stickers/galmax/froggie-vibing-gif.gif', 'image/gif'),
    BundledSticker('froggie_wave', 'assets/stickers/galmax/froggie-wave.png', 'image/png'),
  ]),
  BundledStickerPack('Gopha', [
    BundledSticker('gopha_bye', 'assets/stickers/galmax/gopha-bye.png', 'image/png'),
    BundledSticker('gopha_cry', 'assets/stickers/galmax/gopha-cry.png', 'image/png'),
    BundledSticker('gopha_good_morning', 'assets/stickers/galmax/gopha-good-morning.png', 'image/png'),
    BundledSticker('gopha_hi', 'assets/stickers/galmax/gopha-hi.png', 'image/png'),
    BundledSticker('gopha_hide', 'assets/stickers/galmax/gopha-hide.png', 'image/png'),
    BundledSticker('gopha_lovely', 'assets/stickers/galmax/gopha-lovely.png', 'image/png'),
    BundledSticker('gopha_no', 'assets/stickers/galmax/gopha-no.png', 'image/png'),
    BundledSticker('gopha_ok', 'assets/stickers/galmax/gopha-ok.png', 'image/png'),
    BundledSticker('gopha_sleepy', 'assets/stickers/galmax/gopha-sleepy.png', 'image/png'),
    BundledSticker('gopha_sorry', 'assets/stickers/galmax/gopha-sorry.png', 'image/png'),
    BundledSticker('gopha_thank_you', 'assets/stickers/galmax/gopha-thank-you.png', 'image/png'),
    BundledSticker('gopha_work', 'assets/stickers/galmax/gopha-work.png', 'image/png'),
  ]),
  BundledStickerPack('Meow', [
    BundledSticker('meow_bread', 'assets/stickers/galmax/meow-bread.png', 'image/png'),
    BundledSticker('meow_cry', 'assets/stickers/galmax/meow-cry.png', 'image/png'),
    BundledSticker('meow_hello', 'assets/stickers/galmax/meow-hello.png', 'image/png'),
    BundledSticker('meow_hug', 'assets/stickers/galmax/meow-hug.png', 'image/png'),
    BundledSticker('meow_love', 'assets/stickers/galmax/meow-love.png', 'image/png'),
    BundledSticker('meow_nwn', 'assets/stickers/galmax/meow-nwn.png', 'image/png'),
    BundledSticker('meow_ok', 'assets/stickers/galmax/meow-ok.png', 'image/png'),
    BundledSticker('meow_party', 'assets/stickers/galmax/meow-party.gif', 'image/gif'),
    BundledSticker('meow_pat', 'assets/stickers/galmax/meow-pat.png', 'image/png'),
    BundledSticker('meow_peek', 'assets/stickers/galmax/meow-peek.png', 'image/png'),
    BundledSticker('meow_queen', 'assets/stickers/galmax/meow-queen.png', 'image/png'),
    BundledSticker('shiblob_cool', 'assets/stickers/galmax/shiblob-cool.png', 'image/png'),
    BundledSticker('shiblob_evil', 'assets/stickers/galmax/shiblob-evil.png', 'image/png'),
    BundledSticker('shiblob_happy', 'assets/stickers/galmax/shiblob-happy.png', 'image/png'),
    BundledSticker('shiblob_heart_1', 'assets/stickers/galmax/shiblob-heart-1.png', 'image/png'),
    BundledSticker('shiblob_lurk', 'assets/stickers/galmax/shiblob-lurk.png', 'image/png'),
    BundledSticker('shiblob_melt', 'assets/stickers/galmax/shiblob-melt.png', 'image/png'),
    BundledSticker('shiblob_ok', 'assets/stickers/galmax/shiblob-ok.png', 'image/png'),
    BundledSticker('shiblob_peek', 'assets/stickers/galmax/shiblob-peek.png', 'image/png'),
    BundledSticker('shiblob_reach', 'assets/stickers/galmax/shiblob-reach.png', 'image/png'),
    BundledSticker('shiblob_smile', 'assets/stickers/galmax/shiblob-smile.png', 'image/png'),
    BundledSticker('shiblob_thumbs_up', 'assets/stickers/galmax/shiblob-thumbs-up.png', 'image/png'),
    BundledSticker('shiblob_wink', 'assets/stickers/galmax/shiblob-wink.png', 'image/png'),
  ]),
  BundledStickerPack('Parrots', [
    BundledSticker('parrot_60_fps', 'assets/stickers/galmax/parrot-60-fps.gif', 'image/gif'),
    BundledSticker('parrot_chill', 'assets/stickers/galmax/parrot-chill.gif', 'image/gif'),
    BundledSticker('parrot_coffee', 'assets/stickers/galmax/parrot-coffee.gif', 'image/gif'),
    BundledSticker('parrot_conga', 'assets/stickers/galmax/parrot-conga.gif', 'image/gif'),
    BundledSticker('parrot_cool', 'assets/stickers/galmax/parrot-cool.gif', 'image/gif'),
    BundledSticker('parrot_dad', 'assets/stickers/galmax/parrot-dad.gif', 'image/gif'),
    BundledSticker('parrot_deal_with_it', 'assets/stickers/galmax/parrot-deal-with-it.gif', 'image/gif'),
    BundledSticker('parrot_disco', 'assets/stickers/galmax/parrot-disco.gif', 'image/gif'),
    BundledSticker('parrot_donut', 'assets/stickers/galmax/parrot-donut.gif', 'image/gif'),
    BundledSticker('parrot_explody', 'assets/stickers/galmax/parrot-explody.gif', 'image/gif'),
    BundledSticker('parrot_github', 'assets/stickers/galmax/parrot-github.gif', 'image/gif'),
    BundledSticker('parrot_love', 'assets/stickers/galmax/parrot-love.gif', 'image/gif'),
    BundledSticker('parrot_matrix', 'assets/stickers/galmax/parrot-matrix.gif', 'image/gif'),
    BundledSticker('parrot_merged', 'assets/stickers/galmax/parrot-merged.gif', 'image/gif'),
    BundledSticker('parrot_pizza', 'assets/stickers/galmax/parrot-pizza.gif', 'image/gif'),
    BundledSticker('parrot_sad', 'assets/stickers/galmax/parrot-sad.gif', 'image/gif'),
    BundledSticker('parrot_shuffle_party', 'assets/stickers/galmax/parrot-shuffle-party.gif', 'image/gif'),
    BundledSticker('parrot_sleeping', 'assets/stickers/galmax/parrot-sleeping.gif', 'image/gif'),
    BundledSticker('parrot_stable', 'assets/stickers/galmax/parrot-stable.gif', 'image/gif'),
    BundledSticker('parrot_thumbs_up', 'assets/stickers/galmax/parrot-thumbs-up.gif', 'image/gif'),
    BundledSticker('parrot_upvote', 'assets/stickers/galmax/parrot-upvote.gif', 'image/gif'),
    BundledSticker('parrot_wave1', 'assets/stickers/galmax/parrot-wave1.gif', 'image/gif'),
  ]),
  BundledStickerPack('Party', [
    BundledSticker('party_100', 'assets/stickers/galmax/party-100.png', 'image/png'),
    BundledSticker('party_doge', 'assets/stickers/galmax/party-doge.gif', 'image/gif'),
    BundledSticker('party_frog', 'assets/stickers/galmax/party-frog.png', 'image/png'),
    BundledSticker('party_nyan', 'assets/stickers/galmax/party-nyan.gif', 'image/gif'),
    BundledSticker('party_parrot', 'assets/stickers/galmax/party-parrot.gif', 'image/gif'),
    BundledSticker('party_peach', 'assets/stickers/galmax/party-peach.png', 'image/png'),
    BundledSticker('party_sunglasses', 'assets/stickers/galmax/party-sunglasses.png', 'image/png'),
    BundledSticker('party_tada', 'assets/stickers/galmax/party-tada.png', 'image/png'),
  ]),
];
